version: '3.9'
services:
    golang:
        build: ./backend
        container_name: kleon_backend
        ports:
            - 5000:5000
        env_file: .env
        command: air
        restart: on-failure
        depends_on:
            - postgres
        volumes:
            - ./backend:/app
        networks:
            - backend

    migrate:
        build: ./data/migrations
        container_name: kleon_migrations
        command: ['-path', '/migrations', '-database', '$POSTGRES_URL', 'up']
        restart: on-failure
        depends_on:
            - postgres
        volumes:
            - ./data/migrations:/migrations
        networks:
            - backend
        links:
            - postgres

    postgres:
        image: postgres:15.2-alpine
        container_name: kleon_database
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./data/postgresdb:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    postgresdb:

networks:
    backend:
        driver: bridge
